config/routes.rb
Rails.application.routes.draw do
  #devise_for :users

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :posts do
    # collection do
    #   get :art
    # end
    member do
      get :upvote
      get :downvote
      post :create_comment
    end
  end

  get 'art', to: "home#art"
  get 'photography', to: "home#photography"
  get 'animals', to: "home#animals"
  get  'travel', to: "home#travel"
  resources :users
   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@posts = Post.search(params[:q]).paginate(page: params[:page], per_page: 5)
	end

	def art
		category = Category.where(title: 'Art').last
		@posts = category.posts.search(params[:q]).paginate(page: params[:page], per_page: 5)
		render 'index'
	end
	def photography
		category = Category.where(title: 'photography').last

		@posts = category.posts.search(params[:q]).paginate(page: params[:page], per_page: 5)
		render 'index'
	end

	def animals
		category = Category.where(title: 'animals').last
		
		@posts = category.posts.search(params[:q]).paginate(page: params[:page], per_page: 5)
		render 'index'
	end

	def travel
		category =Category.where(title: 'travel').last
		@posts = category.posts.search(params[:q]).paginate(page: params[:page], per_page: 5)
		render 'index'
	end
end

app/views/home/index.html.erb
<!-- 
<h1>Home Page</h1>
< % if user_signed_in? %>
< %= link_to "logout",  destroy_user_session_path, method: :delete %>

< % else %>
< %= link_to "Registration",  new_user_registration_path %>
< %= link_to "login", new_user_session_path %>
< % end %> -->
<div class="m-top10"></div>

<div class="row">

	<div align="center">
		<%= will_paginate @posts %>
	</div>

	<div class="col-md-8">
		<% @posts.each do |post| %>
			<div class="well" id="post_<%= post.id %>">
				<% if post.image.present? %>

				<%= image_tag(post.image.url, class: 'img-responsive') %>

				<% else %>

				<%= image_tag("dummy_img.png") %>

				<% end %>

				<h1><%=  post.name %></h1>

				<p>  <%= post.description %></p>

				<div class="pull-right ">
					<%= link_to 'Comment',  post_path(post) , class: 'm-left10' %>(<%= post.comments.count %>)
				</div>
				<div class="pull-right m-bottom20 post-actions">
					<%= link_to 'Upvote', upvote_post_path(post) %> <span class="upvote-count"> (<%= post.votes.where(vote_type: 'upvote').count %>) </span>
					<%= link_to 'Downvote', downvote_post_path(post), class: 'm-left10' %> <span class="downvote-count"> (<%= post.votes.where(vote_type: 'downvote').count %>)</span>
				</div>
				<div class="clearfix"></div>
			</div>
		<% end %>
	</div>

	<div class="col-md-4">
		<div class="well">
			<div class="sidebar-top clarfix">
				<table class="index-box">
					<div class="well">
            <% if user_signed_in? %>
							<% if current_user.image.present? %>
								<%= image_tag(current_user.image.url, class: 'img-responsive') %>
							<% else %>
								<%= image_tag("dummy_img.png") %>
							<% end %> 
            <% end %>
          </div>
	          
				</table>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	
	jQuery('.post-actions a').on('click', function(event){
		event.preventDefault();
		event.stopPropagation();

		jQuery.ajax({
			url: jQuery(this).attr('href'),
			method: 'get',
			// data: {

			// }
			success: function() {

			},
			error: function() {

			}
		})
	})
</script>