config/routes.rb
Rails.application.routes.draw do
  #devise_for :users

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :posts do
    # collection do
    #   get :art
    # end
    member do
      get :upvote
      get :downvote
      post :create_comment
    end
  end

  get 'art', to: "home#art"
  get 'photography', to: "home#photography"
  get 'animals', to: "home#animals"
  get  'travel', to: "home#travel"
  resources :users
   
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, MediaFileUploader
	
	belongs_to :user
	belongs_to :category
	has_many :votes
  has_many :comments
	def self.search(search)
		if search
			where(['name LIKE ?', "%#{search}%"])
		else
			all
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	layout 'form_layout'

	def index
		
	end


	def new
		@post = Post.new
	end

	def create

		@post  = Post.new(post_params)
		
			@post.user_id  = current_user.id
	
		if  @post.save
			flash[:notice]= "post was successfully created"
			redirect_to  post_path(@post)
		else
			render :new
		end
	end

	def show
		@post = Post.find(params[:id])
		
	end

	def edit
    @post = Post.find(params[:id])
	end

	def update
    @post = Post.find(params[:id])
    
    if @post.update(post_params)
     	flash[:notice] = "post successfully updated"
     	redirect_to post_path(@post)
    else
     	render :edit
    end
	end
		
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		flash[:notice]= "post is successfully deleted"
		redirect_to  posts_path
	end

	def upvote
		@post = Post.find(params[:id])
		vote = Vote.find_or_create_by(user_id: current_user.id, post_id: params[:id])
		vote.vote_type = 'upvote'
		vote.save
		# redirect_to root_path
	end

	def downvote
		@post = Post.find(params[:id])
		vote = Vote.find_or_create_by(user_id: current_user.id, post_id: params[:id])
		vote.vote_type = 'downvote'
		vote.save
		# redirect_to root_path
	end
   
   def create_comment
		post = Post.find(params[:id])
		comment = post.comments.build(params.require(:comment).permit(:content, :image))
		comment.user_id = current_user.id
		comment.save

		redirect_back fallback_location: root_path
	end

	private

	def post_params
		params.require(:post).permit(:name, :description, :category_id, :user_id, :image)
	end
end 

app/views/posts/downvote.js.erb
var upVoteselector = "#post_<%= params[:id] %> .upvote-count";
jQuery(upVoteselector).html("(<%= @post.votes.where(vote_type: 'upvote').count %>)")

var downVoteselector = "#post_<%= params[:id] %> .downvote-count";
jQuery(downVoteselector).html("(<%= @post.votes.where(vote_type: 'downvote').count %>)")

app/views/posts/edit.html.erb
<h1 align="center">Edit existing post</h1>
<%= form_for @post  do  |f| %>
	
	<div class="row">
		<div class="col-xs-12">
			<% if @post.errors.any? %>
				<h2>The following errors prevented the post from getting created</h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-8">
			<div class="form-group">
				<%= f.text_field :name, class: "form-control", placeholder: "Post Title", autofocus: true %>
			</div>
			<div class="form-group">
				<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Title description" %>
			</div>

			<div class="form-group">
				<%= f.file_field :image %>
			</div>

			<div class="form-group">
				<%= f.submit class: "btn btn-primary btn-lg" %>				
			</div>
		</div>
		
	</div>
<% end %>
<div class="row">
	<div class="col-xs-12">
		[<%= link_to 'Cancle request return to post ',  new_post_path %> 

		<%= link_to 'Edit an existing article ',   edit_post_path %>]
	</div>
</div>

app/views/posts/new.html.erb
<%= form_for @post  do  |f| %>
	
	<div class="row">
		<div class="col-xs-12">
			<% if @post.errors.any? %>
				<h2>The following errors prevented the post from getting created</h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-8">
			<div class="form-group">
				<%= f.text_field :name, class: "form-control", placeholder: "Post Title", autofocus: true %>
			</div>
			<div class="form-group">
				<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Title description" %>
			</div>
            
            
			<div class="form-group">
				<%= f.file_field :image %>
			</div>

			<div class="form-group">
				<%= f.submit class: "btn btn-primary btn-lg" %>				
			</div>
		</div>
		<div class="col-xs-4">
			<div class="form-group">
				<%= f.select :category_id, options_for_select(Category.all.map { |category| [category.title, category.id]}), {prompt: 'Choose Category'}, class: "form-control" %><br>
				
			</div>
		</div>
	</div>
<% end %>
<div class="row">
	<div class="col-xs-12">
		[<%= link_to 'Cancle request return to post ',  new_post_path %>] 
	</div>
</div>

app/views/posts/show.html.erb
<div class="row">
	<div class="col-xs-12">
		<p>
 			Title : <%= @post.name %>
 		</p>
 		<p>
 			Description : <%= @post.description %>
 		</p>
	</div>
</div>


 <% if @post.image.present? %>
 	<%= image_tag(@post.image.url) %>
 <% end %>

 <% @post.comments.each do |comment| %>
 	<div class="well">
 		<% if comment.image.present? %>
 			<%= image_tag(comment.image.url, class: 'img-responsive') %>
	 	<% else %>
	 		<%= image_tag("dummy_img.png", class: 'img-responsive') %>
 		<% end %>
 		<p>
 			<%= comment.content %>
 		</p>
 	</div>
 <% end %>


<%= form_for(Comment.new, url: create_comment_post_path(@post)) do |f| %>
	<div class="form-group">
		<%= f.text_area :content, class: "form-control", placeholder: "Write Comment", autofocus: true %>
	</div>

	<div class="form-group">
		<%= f.file_field :image, class: "form-control" %>
	</div>

	<div class="form-group">
		<button type="submit" class="btn btn-default">Post</button>
	</div>

<% end %>

app/views/posts/upvote.js.erb
var upVoteselector = "#post_<%= params[:id] %> .upvote-count";
jQuery(upVoteselector).html("(<%= @post.votes.where(vote_type: 'upvote').count %>)")

var downVoteselector = "#post_<%= params[:id] %> .downvote-count";
jQuery(downVoteselector).html("(<%= @post.votes.where(vote_type: 'downvote').count %>)")