config/routes.rb
Rails.application.routes.draw do
  #devise_for :users

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :posts do
    # collection do
    #   get :art
    # end
    member do
      get :upvote
      get :downvote
      post :create_comment
    end
  end

  get 'art', to: "home#art"
  get 'photography', to: "home#photography"
  get 'animals', to: "home#animals"
  get  'travel', to: "home#travel"
  resources :users
   
end

app/views/layouts/_form_layout_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-BoaredPanda" href="#">
        <%= image_tag("logo.png", style: 'width: 200px; height:auto;') %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Me<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Post", new_post_path %></li>
              <li><%= link_to "My Profile", user_path(current_user) %></li>
              <li><a href="#">Top Users</a></li>
              <li><a href="#">Edit Profile</a></li>
              <li><a href="#">Change Password</a></li>
              <li><a href="#">Notification Setting</a></li>
              <li><a href="#"><%= link_to  'Sign out', destroy_user_session_path , class: "", method: :delete  %></a></li>
            </ul>
          </li>

        <% else %>
          <li><a href="#"><%= link_to  'Login', new_user_session_path, class: "" %></a></li>
        <% end %>
     </ul>
   </div><!-- /.navbar-collapse -->
 </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-BoaredPanda" href="#">
        <%= image_tag("logo.png", style: 'width: 200px; height:auto;') %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
         <!--  <a href="#">Art <span class="sr-only">(current)</span></a> -->
         <%= link_to 'Art', art_path %>
        </li>
        <li><%= link_to 'Photography',  photography_path %></li>
       
        <li><%= link_to 'animals', animals_path %></li>

        <li><%= link_to 'Travel', travel_path %></li> 


        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>

      </ul>
      
      <%= form_tag(request.path, class: 'navbar-form navbar-left', method: :get ) do %>
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="q" value=<%= params[:q] %>>
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      <% end %>
<!--       <form class="navbar-form navbar-left">
      </form> -->

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Me<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Post", new_post_path %></li>
              <!-- <li><a href="#">My Profile</a></li>  -->
              <li><%= link_to "My Profile", user_path(current_user)%></li>
              <li><a href="#">Top Users</a></li>
              <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
               <li><%= link_to "show post", post_path(current_user) %></li>
              <li><a href="#">Change Password</a></li>
              <li><a href="#">Notification Setting</a></li>
              <li><a href="#"><%= link_to  'Sign out', destroy_user_session_path , class: "", method: :delete  %></a></li>
            </ul>
          </li>
        <% else %>
          <!-- <li>< %= link_to  'Login', new_user_session_path %></li> -->
          <li><%= link_to  'Login', 'javascript:void(0)', :"data-toggle" => "modal", :"data-target" => "#loginModal" %></li>
        <% end %>
     </ul>
   </div><!-- /.navbar-collapse -->
 </div><!-- /.container-fluid -->
</nav>



<div id="loginModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Login</h4>
      </div>
      <div class="modal-body">
        <h2>Let's fight boredom together!</h2>
        <div class="form-group">
          <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
          <button class="btn btn-default">Google Login</button>
        </div>
        <div class="form-group">
          <%= link_to "Sign in with google", user_google_oauth2_omniauth_authorize_path %>
          <button class="btn btn-default">Google Login</button>
        </div>
        <div class="clearfix"></div>
        <%= render partial: '/devise/sessions/login_form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/layouts/_navigation1.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-BoaredPanda" href="#">Boared-Panda</a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Art <span class="sr-only">(current)</span></a></li>
       
       <li><a href="#">Photography</a></li>
       <li><a href="#">Animal</a></li>



        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> 
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardPanda</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="notice" style="position: absolute;"><%= notice %></p>
    <p class="alert" style="position: absolute;"><%= alert %></p>
    <%= image_tag("header-background.jpg", :alt => "header-background", style: "width:100%;height:200px;") %>
    <%= render 'layouts/navigation' %>
    <!-- < %= render 'layouts/form_layout_navigation'%> --> 
    <div class="grey-bg">
      <div class="container">
        <% flash.each do |name, msg|%>
          <ul><li><%= msg %></li></ul>
        <% end%>
     
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/form_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardPanda</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="notice" style="position: absolute;"><%= notice %></p>
    <p class="alert" style="position: absolute;"><%= alert %></p>
    <%= render 'layouts/form_layout_navigation' %>
    <!-- < %= render 'layouts/navigation1'%> -->
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/user_layout_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-BoaredPanda" href="#">
        <%= image_tag("logo.png", style: 'width: 200px; height:auto;') %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Me<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Post", new_post_path %></li>
              <li><a href="#">My Profile</a></li>
              <li><a href="#">Top Users</a></li>
              <li><%= link_to "Edit profile", edit_user_path %></li>
              <li><a href="#">Change Password</a></li>  `
              <li><a href="#">Notification Setting</a></li>
              <li><a href="#"><%= link_to  'Sign out', destroy_user_session_path , class: "", method: :delete  %></a></li>
            </ul>
          </li>

        <% else %>
          <li><a href="#"><%= link_to  'Login', new_user_session_path, class: "" %></a></li>
        <% end %>
     </ul>
   </div><!-- /.navbar-collapse -->
 </div><!-- /.container-fluid -->
</nav>